# Inserts a blank line between shell prompts
add_newline = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[character] 
success_symbol = "ğŸ‘¾"  
error_symbol = "ğŸ’€"

# AWS config
[aws]
format = "on [$region]($style) "
style = "bold blue"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = "[$symbol $branch]($style) "
symbol = "ğŸŒ±"
style = "bold orange"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[hostname]
ssh_only = false
format = "hostname $hostname(bold red) "
style = "bold dimmed white"
disabled = true

[ruby]
format = "using $symbol "
symbol = "ğŸ’"

[python]
format = "using $symbol "
symbol = "ğŸ"
