# Inserts a blank line between shell prompts
add_newline = true

[package]
disabled = true

[character] 
success_symbol = "ğŸ‘¾"  
error_symbol = "ğŸ’€"

[aws]
disabled = true

[directory]
truncation_length = 5
format = "[$path]($style) "
style = "bold purple"

[git_branch]
format = "[$symbol $branch]($style) "
symbol = "ïŠ–"
style = "bold blue"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[ruby]
format = "using $symbol "
symbol = "ğŸ’"
disabled = true

[python]
format = "using $symbol "
symbol = "ğŸ"
disabled = true

[terraform]
disabled = true
